name = "unbird"
compatibility_date = "2026-04-04"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

# Serve the Vite frontend as static assets
[assets]
directory = "./dist"

[vars]
UNBIRD_HMAC_KEY = "your-secret-key-change-me-later"

[[kv_namespaces]]
binding = "UNBIRD_SESSIONS"
id = "35683496ea164e2eb8210607897b859b"

[[kv_namespaces]]
binding = "UNBIRD_CACHE"
id = "b9405727692d43698c544bfb9b46adde"

[triggers]
crons = ["*/5 * * * *"]
